#ifndef HACKERNEL_FILE_DEFINE_H
#define HACKERNEL_FILE_DEFINE_H

enum {
    FILE_A_UNSPEC,
    FILE_A_SESSION,

    FILE_A_STATUS_CODE,
    FILE_A_OP_TYPE,
    FILE_A_NAME,
    FILE_A_PERM,
    __FILE_A_MAX,
};
#define FILE_A_MAX (__FILE_A_MAX - 1)

#endif
