/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef HACKERNEL_KEEPALIVE_DEFINE_H
#define HACKERNEL_KEEPALIVE_DEFINE_H

#include "hackernel/util.h"

EXTERN_C_BEGIN

enum {
    HANDSHAKE_A_UNSPEC,
    HANDSHAKE_A_STATUS_CODE,
    HANDSHAKE_A_SYS_SERVICE_TGID,
    __HANDSHAKE_A_MAX,
};
#define HANDSHAKE_A_MAX (__HANDSHAKE_A_MAX - 1)
#define HEARTBEAT_INTERVAL 1000

EXTERN_C_END

#endif
