#ifndef HACKERNEL_KEEPALIVE_DEFINE_H
#define HACKERNEL_KEEPALIVE_DEFINE_H

enum {
    HANDSHAKE_A_UNSPEC,
    HANDSHAKE_A_STATUS_CODE,
    HANDSHAKE_A_SYS_SERVICE_TGID,
    __HANDSHAKE_A_MAX,
};
#define HANDSHAKE_A_MAX (__HANDSHAKE_A_MAX - 1)

#endif
